CREATE TABLE IF NOT EXISTS device_latest_state (
    device_id TEXT PRIMARY KEY,
    temperature DOUBLE PRECISION, humidity DOUBLE PRECISION, lux DOUBLE PRECISION,
    x DOUBLE PRECISION, y DOUBLE PRECISION, z DOUBLE PRECISION,
    ammonia DOUBLE PRECISION, nitrogen DOUBLE PRECISION, phosphorus DOUBLE PRECISION,
    potassium DOUBLE PRECISION, moisture DOUBLE PRECISION, ec DOUBLE PRECISION,
    ph DOUBLE PRECISION, salinity DOUBLE PRECISION, speed DOUBLE PRECISION,
    distance DOUBLE PRECISION, last_packet_id INTEGER, last_seen TIMESTAMPTZ
);